const members = [
  {
    _id: 1,
    firstName: "Lorenze",
    lastName: "Hernandez",
    gradeYear: "Jr.",
    workshop: "Discord Bot",
    timesAttended: 5,
  },
  {
    _id: 2,
    firstName: "Gordon",
    lastName: "Ramsey",
    gradeYear: "Jr.",
    workshop: "Minecraft Game",
    timesAttended: 2,
  },
  {
    _id: 3,
    firstName: "Wick",
    lastName: "John",
    gradeYear: "Sr.",
    workshop: "Discord Bot",
    timesAttended: 6,
  },
  {
    _id: 4,
    firstName: "John",
    lastName: "Snow",
    gradeYear: "Fr.",
    workshop: "Discord Bot",
    timesAttended: 3,
  },
  {
    _id: 5,
    firstName: "Hydro",
    lastName: "Flask",
    gradeYear: "Soph.",
    workshop: "Minecraft Game",
    timesAttended: 5,
  },
  {
    _id: 6,
    firstName: "Mary",
    lastName: "Littlelam",
    gradeYear: "Fr.",
    workshop: "Discord Bot",
    timesAttended: 5,
  },
  {
    _id: 7,
    firstName: "Bay",
    lastName: "Max",
    gradeYear: "Sr.",
    workshop: "Minecraft Game",
    timesAttended: 5,
  },
  {
    _id: 8,
    firstName: "Justin",
    lastName: "Beiber",
    gradeYear: "Jr.",
    workshop: "Minecraft Game",
    timesAttended: 5,
  },
  {
    _id: 9,
    firstName: "Russel",
    lastName: "Wilson",
    gradeYear: "Soph.",
    workshop: "Discord Bot",
    timesAttended: 2,
  },
  {
    _id: 10,
    firstName: "Jordyn",
    lastName: "Woods",
    gradeYear: "Soph.",
    workshop: "Discord Bot",
    timesAttended: 5,
  },
  {
    _id: 11,
    firstName: "Johhny",
    lastName: "Laurence",
    gradeYear: "Senior.",
    workshop: "Minecraft Game",
    timesAttended: 2,
  },
  {
    _id: 12,
    firstName: "Johhny",
    lastName: "Laurence",
    gradeYear: "Senior.",
    workshop: "Minecraft Game",
    timesAttended: 2,
  },
  {
    _id: 13,
    firstName: "Johhny",
    lastName: "Laurence",
    gradeYear: "Senior.",
    workshop: "Minecraft Game",
    timesAttended: 2,
  },
  {
    _id: 14,
    firstName: "Johhny",
    lastName: "Laurence",
    gradeYear: "Senior.",
    workshop: "Minecraft Game",
    timesAttended: 2,
  },
  {
    _id: 15,
    firstName: "Johhny",
    lastName: "Laurence",
    gradeYear: "Senior.",
    workshop: "Minecraft Game",
    timesAttended: 2,
  },
  {
    _id: 16,
    firstName: "Johhny",
    lastName: "Laurence",
    gradeYear: "Senior.",
    workshop: "Minecraft Game",
    timesAttended: 2,
  },
  {
    _id: 17,
    firstName: "Johhny",
    lastName: "Laurence",
    gradeYear: "Senior.",
    workshop: "Minecraft Game",
    timesAttended: 2,
  },
  {
    _id: 18,
    firstName: "Johhny",
    lastName: "Laurence",
    gradeYear: "Senior.",
    workshop: "Minecraft Game",
    timesAttended: 2,
  },
  {
    _id: 19,
    firstName: "Johhny",
    lastName: "Laurence",
    gradeYear: "Senior.",
    workshop: "Minecraft Game",
    timesAttended: 2,
  },
  {
    _id: 20,
    firstName: "Johhny",
    lastName: "Laurence",
    gradeYear: "Senior.",
    workshop: "Minecraft Game",
    timesAttended: 2,
  },
  {
    _id: 21,
    firstName: "Johhny",
    lastName: "Laurence",
    gradeYear: "Senior.",
    workshop: "Minecraft Game",
    timesAttended: 2,
  },
];

export default members;
